In [2]:
import sys, os
sys.path.append('/Users/derek/projects/deep-learning-from-scratch')
import numpy as np
from dataset.mnist import load_mnist

In [3]:
(x_train, t_train), (x_test, t_test) = (
    load_mnist(normalize=True, one_hot_label=True))

In [7]:
train_size = x_train.shape[0]
batch_size = 10
batch_mask = np.random.choice(train_size, batch_size)

In [13]:
x_batch = x_train[batch_mask]
x_batch[:, 300:310]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.972549  , 0.24705882, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.79607844, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.99215686, 0.89411765, 0.48235294, 0.07058824, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.75686276, 0.39607844, 0.1882353

In [15]:
def numerical_diff(f, x):
    h = 1e-4
    return (f(x+h) - f(x-h)) / (2*h)

In [16]:
def function_2(x0, x1):
    return x0 ** 2 + x1 **2

## Use can you partial function!

In [17]:
from functools import partial

In [19]:
fn_2_tmp1 = partial(function_2, x1=4)

In [20]:
numerical_diff(fn_2_tmp1, 3)

6.00000000000378

In [21]:
def numerical_gradient(f, x):
    h = 1e-4
    grad = np.zeros_like(x)
    
    for idx in range(x.size):
        tmp_val = x[idx]
        
        x[idx] = tmp_val + h
        fx_h1 = f(x)
        
        x[idx] = tmp_val - h
        fx_h2 = f(x)
        
        grad[idx] = (fx_h1 - fx_h2) / (2*h)
        x[idx] = tmp_val
    return grad

In [23]:
def function_2(x):
    return x[0] ** 2 + x[1] **2

In [24]:
numerical_gradient(function_2, np.array([3.0, 4.0]))

array([6., 8.])

In [26]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
    x = init_x
    for i in range(step_num):
        if i % 10 == 0:
            print(x)
        grad = numerical_gradient(f, x)
        x -= lr * grad
    return x

In [27]:
x = np.array([3.0, 4.0])
gradient_descent(function_2, x)

[3. 4.]
[2.45121842 3.26829123]
[2.00282392 2.67043189]
[1.63645296 2.18193728]
[1.33710121 1.78280162]
[1.09250904 1.45667872]
[0.89265943 1.19021257]
[0.72936774 0.97249033]
[0.59594655 0.7945954 ]
[0.48693172 0.64924229]


array([0.39785867, 0.53047822])

In [28]:
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [ ]:
class SimpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)
    
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss

In [29]:
np.random.randn(2, 3)

array([[-0.79126975, -0.8114008 ,  1.54367876],
       [-0.03968206,  0.33102451,  0.97146417]])

In [30]:
import torch

In [38]:
torch.matmul(torch.randn(2,3),torch.tensor([0.1, 0.2]), )

RuntimeError: size mismatch, [2 x 3], [2] at /Users/soumith/code/builder/wheel/pytorch-src/aten/src/TH/generic/THTensorMath.cpp:1965