# Numpy basics

Numpy is a backbone for number-crunching applications. It is heavily used where the speed is important!

In [1]:
import numpy as np

In [2]:
x = np.array([1., 2., 3.])  # np.array is wrapper for a C array
y = np.array([1., 2., 3.])
print(x)

[1. 2. 3.]


### What are vector, matrix, and tensor?
- vector: 1d array
- matrix: 2d array
- tensor: nd array

In [3]:
# How these two should be printed?
# print(x.reshape(1,3,1))
# print(np.random.normal(size=(2,2,3)))

### Windowing: slicing, indexing

In [4]:
x_view = x[:2]  # copy involed?
x[0] = -1.0
# print(x_view)

### [Broadcasting](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#ufuncs-broadcasting)

3 cases
- The arrays all have exactly the same shape.
- The arrays all have the same number of dimensions and the length of each dimensions is either a common length or 1.
- The arrays that have too few dimensions can have their shapes prepended with a dimension of length 1 to satisfy property 2.

In [5]:
# case 2
x1 = np.array(range(8)).reshape(2,4,1)
x2 = np.array([10, 20]).reshape(2,1,1)
print(x1)
print(x2)

[[[0]
  [1]
  [2]
  [3]]

 [[4]
  [5]
  [6]
  [7]]]
[[[10]]

 [[20]]]


In [6]:
# print(x1 + x2)

In [7]:
# case 3
x1 = np.array(range(8)).reshape(2,4,1)
x2 = (np.array(range(2)) * 2)
print(x1)
print(x2)

[[[0]
  [1]
  [2]
  [3]]

 [[4]
  [5]
  [6]
  [7]]]
[0 2]


In [8]:
# x1 + x2

### [np.matmul](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html)

- If the first argument is 1-D, it is promoted to a matrix by prepending a 1 to its dimensions. After matrix multiplication the prepended 1 is removed.
- If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions. After matrix multiplication the appended 1 is removed.
- If either argument is N-D, N > 2, it is treated as a stack of matrices residing in the last two indexes and broadcast accordingly.

In [9]:
x = np.array([1,2,3])
# print(np.matmul(x,x))

In [10]:
x = np.array(range(4)).reshape(2,2)
y = np.array([10, 20])
print(x)
print(y)

[[0 1]
 [2 3]]
[10 20]


In [11]:
# print(np.matmul(x,y))
# print(np.matmul(y,x))

In [12]:
x = np.array(range(9)).reshape(3,1,3)
y = np.array([4,5,6]).reshape(3,1)
print(x)
print(y)

[[[0 1 2]]

 [[3 4 5]]

 [[6 7 8]]]
[[4]
 [5]
 [6]]


In [13]:
print(np.matmul(x, y))
print(np.matmul(y, x))

[[[ 17]]

 [[ 62]]

 [[107]]]
[[[ 0  4  8]
  [ 0  5 10]
  [ 0  6 12]]

 [[12 16 20]
  [15 20 25]
  [18 24 30]]

 [[24 28 32]
  [30 35 40]
  [36 42 48]]]


# More on
### 1. Make a function to get the consine similarity(distance) between two matrices
### 2. How getitem is implemented in Python