In [1]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct  3 21:27:31 2018

@author: sungyunlee
"""

import numpy as np

A = np.array([[1,2], [3,4], [5,6]])
print(A)
print(np.ndim(A))
print(A.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [2]:
A = np.array([[1,2], [3,4]])
print(A.shape)
B = np.array([[5,6], [7,8]])
print(B.shape)
print(np.dot(A, B))

(2, 2)
(2, 2)
[[19 22]
 [43 50]]


In [3]:
A = np.array([[1,2,3], [4,5,6]])
print(A.shape)
B = np.array([[1,2], [3,4], [5,6]])
print(B.shape)
print(np.dot(A, B))

(2, 3)
(3, 2)
[[22 28]
 [49 64]]


In [4]:
A = np.array([[1,2,3], [4,5,6]])
print(A.shape)

C = np.array([[1,2], [3,4]])
print(C.shape)
print(A.shape)
print(np.dot(A, C))

(2, 3)
(2, 2)
(2, 3)


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [5]:
A = np.array([[1,2], [3,4], [5,6]])
print(A.shape)
B = np.array([7,8])
print(B.shape)
print(np.dot(A, B))

(3, 2)
(2,)
[23 53 83]


In [6]:
X = np.array([1,2])
print(X.shape)
W = np.array([[1,3,5], [2,4,6]])
print(W.shape)
Y = np.dot(A, B)
print(Y)

(2,)
(2, 3)
[23 53 83]
