In [1]:
import tensorflow as tf
import numpy as np


In [10]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,0:3]
y_data = xy[:,[-1]]

x = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.placeholder(tf.float32, shape=[None, 1])
w = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(x,w) + b
cost = tf.reduce_mean(tf.square(hypothesis - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(5001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x:x_data, y:y_data})
    #print(cost_val, hy_val)
print(sess.run(hypothesis, feed_dict={x:[[73,80,75], [89,91,90]]}))

[[ 152.82009888]
 [ 181.55639648]]


In [13]:
print(x_data.shape)
print(y_data.shape)
y_data

(25, 3)
(25, 1)


array([[ 152.],
       [ 185.],
       [ 180.],
       [ 196.],
       [ 142.],
       [ 101.],
       [ 149.],
       [ 115.],
       [ 175.],
       [ 164.],
       [ 141.],
       [ 141.],
       [ 184.],
       [ 152.],
       [ 148.],
       [ 192.],
       [ 147.],
       [ 183.],
       [ 177.],
       [ 159.],
       [ 177.],
       [ 175.],
       [ 175.],
       [ 149.],
       [ 192.]], dtype=float32)

In [9]:
print(x)

print(y)
print(w)
print(b)

Tensor("Placeholder_6:0", shape=(?, 3), dtype=float32)
Tensor("Placeholder_7:0", shape=(?, 1), dtype=float32)
<tf.Variable 'weight_3:0' shape=(3, 1) dtype=float32_ref>
<tf.Variable 'bias_3:0' shape=(1,) dtype=float32_ref>


In [3]:
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], shuffle=False, name='filename_queue')
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)
record_defaults = [[0.],[0.],[0.],[0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
print(train_x_batch)
print(train_y_batch)

Tensor("batch:0", shape=(10, 3), dtype=float32)
Tensor("batch:1", shape=(10, 1), dtype=float32)


In [5]:
x = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.placeholder(tf.float32, shape=[None, 1])
w = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(x,w) + b
cost = tf.reduce_mean(tf.square(hypothesis - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)
for step in range(100):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x:x_batch, y:y_batch})
    #print(cost_val, hy_val)
print(sess.run(hypothesis, feed_dict={x:[[73,80,75], [89,91,90]]}))


[[ 161.19729614]
 [ 183.83213806]]
