In [1]:
import tensorflow as tf
import matplotlib.pylab as plt
import numpy as np


In [14]:
#3 inputs

# x1 x2 x3 y

#H(x1,x2,x3) = w1x1 + w2x2 + w3x3 +b


x1_data = [73,93,89,96,73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]
y_data = [152,185,180,196,142]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y =  tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weights1')
w2 = tf.Variable(tf.random_normal([1]), name='weights2')
w3 = tf.Variable(tf.random_normal([1]), name='weights3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2000):
    cost_val, hy_val,_ = sess.run([cost, hypothesis, train], feed_dict={x1:x1_data,x2:x2_data,x3:x3_data,Y:y_data})
    print(cost_val, hy_val)
sess.close()


150421.0 [-191.84707642 -229.31188965 -226.27281189 -249.38008118 -172.32287598]
47149.8 [-40.38245773 -47.26272964 -46.89666367 -54.04391098 -33.465271  ]
14779.8 [ 44.41701889  54.65988159  53.52945709  55.31764984  44.27597809]
4633.5 [  91.89313507  111.72263336  109.7543335   116.5451889    87.8004303 ]
1453.18 [ 118.4732666   143.66995239  141.23258972  150.82427979  112.16815186]
456.321 [ 133.35450745  161.55607605  158.85609436  170.01586914  125.81070709]
143.857 [ 141.68598938  171.56987     168.72286987  180.76057434  133.44866943]
45.9167 [ 146.35046387  177.17619324  174.24688721  186.77616882  137.72483826]
15.2174 [ 148.96192932  180.3150177   177.33958435  190.14408875  140.11891174]
5.59484 [ 150.42401123  182.07228088  179.07107544  192.02966309  141.45922852]
2.57861 [ 151.24256897  183.05610657  180.04048157  193.08537292  142.20959473]
1.63313 [ 151.70088196  183.60693359  180.58322144  193.67645264  142.62969971]
1.33676 [ 151.95744324  183.9152832   180.88703918

1.1921 [ 152.28479004  184.30603027  181.2727356   194.43643188  143.15464783]
1.19203 [ 152.28479004  184.30601501  181.27270508  194.43647766  143.15458679]
1.19199 [ 152.28479004  184.30599976  181.27272034  194.4365387   143.15455627]
1.19193 [ 152.2848053   184.30601501  181.27272034  194.43658447  143.15449524]
1.1919 [ 152.2848053   184.3059845   181.27270508  194.43659973  143.15444946]
1.19186 [ 152.2848053   184.3059845   181.27272034  194.43664551  143.15438843]
1.1918 [ 152.2848053   184.3059845   181.27270508  194.43669128  143.15434265]
1.19174 [ 152.2848053   184.30596924  181.27268982  194.43673706  143.15429688]
1.19169 [ 152.28482056  184.30596924  181.27268982  194.43678284  143.15423584]
1.19166 [ 152.28482056  184.30595398  181.27270508  194.43682861  143.15420532]
1.1916 [ 152.28483582  184.30595398  181.27270508  194.43687439  143.15414429]
1.19155 [ 152.28485107  184.30593872  181.27267456  194.43692017  143.15411377]
1.19149 [ 152.28485107  184.30593872  181.27

1.18272 [ 152.28552246  184.30459595  181.27180481  194.44462585  143.14533997]
1.18267 [ 152.28552246  184.30458069  181.27178955  194.44465637  143.14527893]
1.18261 [ 152.28553772  184.30458069  181.27178955  194.44471741  143.14523315]
1.18256 [ 152.28553772  184.30458069  181.27178955  194.44476318  143.14518738]
1.18251 [ 152.28553772  184.30458069  181.27175903  194.44477844  143.14512634]
1.18245 [ 152.28553772  184.30458069  181.27178955  194.44487     143.14509583]
1.1824 [ 152.28555298  184.30458069  181.27177429  194.44490051  143.14503479]
1.18237 [ 152.28553772  184.30455017  181.27177429  194.44493103  143.14498901]
1.18232 [ 152.28553772  184.30453491  181.27175903  194.44494629  143.14491272]
1.18228 [ 152.28555298  184.30453491  181.27175903  194.44500732  143.14489746]
1.18222 [ 152.28555298  184.30451965  181.27172852  194.44503784  143.14483643]
1.18215 [ 152.28556824  184.30453491  181.27172852  194.44511414  143.14479065]
1.18211 [ 152.28555298  184.30451965  181

1.17321 [ 152.28607178  184.30332947  181.27079773  194.45294189  143.1360321 ]
1.17316 [ 152.28608704  184.30332947  181.27079773  194.45298767  143.13597107]
1.17312 [ 152.28607178  184.30331421  181.27078247  194.45301819  143.13592529]
1.17305 [ 152.28607178  184.30328369  181.27076721  194.45307922  143.13586426]
1.17301 [ 152.28607178  184.30328369  181.27076721  194.453125    143.13583374]
1.17296 [ 152.28608704  184.30329895  181.27076721  194.45317078  143.13578796]
1.17291 [ 152.28608704  184.30329895  181.27076721  194.45321655  143.13574219]
1.17286 [ 152.28608704  184.30328369  181.27075195  194.45324707  143.13569641]
1.17281 [ 152.28608704  184.30328369  181.27075195  194.45329285  143.13563538]
1.17276 [ 152.28608704  184.30326843  181.27075195  194.45333862  143.1355896 ]
1.1727 [ 152.28607178  184.30325317  181.27072144  194.45336914  143.13552856]
1.17266 [ 152.28608704  184.30323792  181.27072144  194.45341492  143.13548279]
1.17261 [ 152.28608704  184.30323792  181

1.16371 [ 152.28640747  184.30218506  181.26972961  194.46130371  143.12684631]
1.16367 [ 152.28639221  184.3021698   181.26971436  194.46133423  143.12680054]
1.16362 [ 152.28639221  184.30218506  181.26971436  194.46136475  143.12675476]
1.16359 [ 152.28639221  184.30215454  181.2696991   194.46139526  143.12672424]
1.16353 [ 152.28640747  184.30218506  181.2696991   194.4614563   143.12667847]
1.16348 [ 152.28640747  184.30215454  181.26968384  194.46148682  143.12661743]
1.16342 [ 152.28639221  184.30213928  181.26966858  194.46153259  143.1265564 ]
1.16338 [ 152.28639221  184.30213928  181.26966858  194.46156311  143.12651062]
1.16333 [ 152.28640747  184.30215454  181.26966858  194.46162415  143.1264801 ]
1.16328 [ 152.28640747  184.30215454  181.26966858  194.46166992  143.12643433]
1.16324 [ 152.28642273  184.30213928  181.26966858  194.4617157   143.12638855]
1.16318 [ 152.28640747  184.30213928  181.26966858  194.46177673  143.12635803]
1.16314 [ 152.28639221  184.30210876  18

1.15465 [ 152.28651428  184.3012085   181.26861572  194.4692688   143.11817932]
1.1546 [ 152.28651428  184.30122375  181.26860046  194.46929932  143.11813354]
1.15454 [ 152.28651428  184.3012085   181.26858521  194.46936035  143.11810303]
1.15451 [ 152.28651428  184.3012085   181.26860046  194.46939087  143.11804199]
1.15446 [ 152.28649902  184.3012085   181.26860046  194.46943665  143.11799622]
1.15441 [ 152.28649902  184.30119324  181.26856995  194.4694519   143.11795044]
1.15435 [ 152.28648376  184.30117798  181.26855469  194.46951294  143.11790466]
1.15432 [ 152.28649902  184.30116272  181.26855469  194.46954346  143.11785889]
1.15427 [ 152.28648376  184.30116272  181.26855469  194.46958923  143.11781311]
1.15423 [ 152.28649902  184.30117798  181.26855469  194.46961975  143.11776733]
1.15417 [ 152.28649902  184.30116272  181.26855469  194.46968079  143.11772156]
1.15413 [ 152.28649902  184.30114746  181.26853943  194.4697113   143.11767578]
1.15408 [ 152.28649902  184.30116272  181

1.14545 [ 152.28640747  184.300354    181.26741028  194.47737122  143.10949707]
1.1454 [ 152.28642273  184.30036926  181.26742554  194.47743225  143.10945129]
1.14536 [ 152.28642273  184.30036926  181.26741028  194.47746277  143.10942078]
1.14529 [ 152.28642273  184.300354    181.26739502  194.4775238   143.10935974]
1.14527 [ 152.28643799  184.300354    181.26741028  194.47755432  143.10932922]
1.14521 [ 152.28642273  184.30033875  181.26739502  194.4776001   143.10928345]
1.14517 [ 152.28642273  184.300354    181.26737976  194.47763062  143.10925293]
1.14512 [ 152.28642273  184.300354    181.26739502  194.47769165  143.10920715]
1.14508 [ 152.28642273  184.300354    181.26737976  194.47770691  143.10914612]
1.14502 [ 152.28642273  184.30030823  181.26733398  194.47775269  143.10910034]
1.14498 [ 152.28640747  184.30032349  181.2673645   194.47781372  143.10906982]
1.14493 [ 152.28642273  184.30032349  181.26734924  194.47784424  143.10902405]
1.14487 [ 152.28640747  184.30030823  181

1.13635 [ 152.28614807  184.2996521   181.26617432  194.48542786  143.10102844]
1.13631 [ 152.28614807  184.2996521   181.26615906  194.48545837  143.10098267]
1.13626 [ 152.28616333  184.29963684  181.2661438   194.48548889  143.10093689]
1.13623 [ 152.28614807  184.29962158  181.26615906  194.48553467  143.10090637]
1.13617 [ 152.28614807  184.29963684  181.2661438   194.48558044  143.1008606 ]
1.13614 [ 152.28616333  184.29962158  181.26615906  194.48562622  143.10081482]
1.13608 [ 152.28613281  184.29962158  181.26612854  194.48565674  143.10076904]
1.13604 [ 152.28614807  184.29960632  181.26612854  194.48570251  143.10072327]
1.13598 [ 152.28614807  184.29962158  181.26612854  194.48576355  143.10067749]
1.13595 [ 152.28613281  184.29960632  181.26612854  194.48577881  143.10063171]
1.1359 [ 152.28613281  184.29960632  181.26611328  194.48582458  143.1006012 ]
1.13585 [ 152.28613281  184.29960632  181.26609802  194.48587036  143.10055542]
1.13582 [ 152.28613281  184.29959106  181

1.1286 [ 152.28579712  184.29911804  181.26506042  194.49229431  143.09385681]
1.12856 [ 152.28578186  184.29911804  181.26507568  194.49234009  143.09381104]
1.1285 [ 152.28578186  184.29910278  181.26504517  194.49240112  143.09378052]
1.12845 [ 152.28578186  184.29908752  181.26502991  194.49243164  143.09373474]
1.12842 [ 152.28579712  184.29910278  181.26504517  194.49247742  143.09370422]
1.12837 [ 152.28578186  184.29911804  181.26504517  194.49250793  143.09365845]
1.12831 [ 152.2857666   184.29910278  181.26501465  194.49255371  143.09361267]
1.12826 [ 152.2857666   184.29908752  181.26501465  194.49259949  143.09355164]
1.12822 [ 152.2857666   184.29908752  181.26501465  194.49264526  143.09350586]
1.12817 [ 152.28578186  184.29911804  181.26501465  194.49269104  143.09347534]
1.12814 [ 152.28575134  184.29908752  181.26499939  194.4927063   143.09342957]
1.12808 [ 152.28575134  184.29910278  181.26498413  194.49275208  143.09339905]
1.12805 [ 152.2857666   184.29908752  181.

1.1199 [ 152.28523254  184.29862976  181.26377869  194.50006104  143.0859375 ]
1.11985 [ 152.28523254  184.29864502  181.26377869  194.50010681  143.08589172]
1.1198 [ 152.28523254  184.29864502  181.26377869  194.50013733  143.08583069]
1.11976 [ 152.28523254  184.29862976  181.26376343  194.50018311  143.08580017]
1.1197 [ 152.28521729  184.29862976  181.26373291  194.50021362  143.08575439]
1.11967 [ 152.28521729  184.29864502  181.26373291  194.50024414  143.08572388]
1.11961 [ 152.28520203  184.29862976  181.26373291  194.50030518  143.08566284]
1.11957 [ 152.28520203  184.29862976  181.26371765  194.50033569  143.08563232]
1.11953 [ 152.28520203  184.2986145   181.26373291  194.50039673  143.08560181]
1.11948 [ 152.28518677  184.29862976  181.26371765  194.50042725  143.08555603]
1.11944 [ 152.28518677  184.2986145   181.26370239  194.50045776  143.08551025]
1.11939 [ 152.28520203  184.2986145   181.26371765  194.5005188   143.08546448]
1.11935 [ 152.28517151  184.2986145   181.2

1.11124 [ 152.28450012  184.29823303  181.2624054   194.50773621  143.07809448]
1.1112 [ 152.28450012  184.29826355  181.2624054   194.50778198  143.07806396]
1.11115 [ 152.28450012  184.29824829  181.2624054   194.50782776  143.07801819]
1.11111 [ 152.2844696   184.29824829  181.2624054   194.50787354  143.07798767]
1.11105 [ 152.2844696   184.29824829  181.26239014  194.50793457  143.07795715]
1.11103 [ 152.2844696   184.29824829  181.26239014  194.50793457  143.07789612]
1.11097 [ 152.28445435  184.29823303  181.26237488  194.50799561  143.0778656 ]
1.11092 [ 152.2844696   184.29826355  181.26237488  194.50804138  143.07783508]
1.1109 [ 152.28443909  184.29821777  181.26235962  194.50804138  143.07777405]
1.11083 [ 152.28443909  184.29824829  181.26235962  194.50811768  143.07774353]
1.11078 [ 152.28443909  184.29823303  181.2623291   194.50814819  143.07769775]
1.11074 [ 152.28443909  184.29821777  181.2623291   194.50819397  143.07765198]
1.11069 [ 152.28443909  184.29823303  181.

In [18]:
x_data = [[73,80,75],[93,88,93],[89,91,90],[96,98,100],[73,66,70]]
y_data = [[152],[185],[180],[196],[142]]
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])
W = tf.Variable(tf.random_normal([3,1]), name='weight')
B = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X,W) +B
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, train_val,w_val, b_val = sess.run([cost, hypothesis, train, W, B], feed_dict={X:x_data, Y:y_data})
    print(cost_val, hy_val, train_val, w_val, b_val)

34772.0 [[-12.79985619]
 [-15.20237923]
 [-15.27001762]
 [-15.1770649 ]
 [-12.57580566]] None [[-0.45824161]
 [-0.17851193]
 [ 0.45502272]] [ 0.80602884]
6.43284e+07 [[ 7269.19384766]
 [ 8737.30957031]
 [ 8608.67871094]
 [ 9376.08789062]
 [ 6663.41064453]] None [[ 31.37586975]
 [ 31.60898018]
 [ 32.651474  ]] [ 1.17643893]
1.19019e+11 [[-305958.4375 ]
 [-367738.8125 ]
 [-362339.71875]
 [-394577.4375 ]
 [-280493.03125]] None [[-1337.59375   ]
 [-1336.0111084 ]
 [-1352.24584961]] [-14.74343491]
2.20206e+14 [[ 13167111.]
 [ 15825885.]
 [ 15593514.]
 [ 16980946.]
 [ 12071164.]] None [[ 57547.1484375 ]
 [ 57490.046875  ]
 [ 58217.26953125]] [ 670.04162598]
4.0742e+17 [[ -5.66359040e+08]
 [ -6.80721344e+08]
 [ -6.70726400e+08]
 [ -7.30404224e+08]
 [ -5.19218944e+08]] None [[-2475301.5 ]
 [-2472835.  ]
 [-2504086.25]] [-28785.06835938]
7.53798e+20 [[  2.43611914e+10]
 [  2.92803359e+10]
 [  2.88504156e+10]
 [  3.14173788e+10]
 [  2.23335219e+10]] None [[  1.06471816e+08]
 [  1.06365752e+08]
 

nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ n

nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ n

nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ n

nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ n

nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ n

nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ n

nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ n

nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ n

nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ n

nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ n

nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ n

nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]
nan [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]] None [[ nan]
 [ nan]
 [ nan]] [ nan]


In [2]:
import tensorflow as tf


In [10]:
# Lab 4 Multi-variable linear regression

tf.set_random_seed(777)  # for reproducibility


x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

'''
0 Cost:  19614.8
Prediction:
 [ 21.69748688  39.10213089  31.82624626  35.14236832  32.55316544]
10 Cost:  14.0682
Prediction:
 [ 145.56100464  187.94958496  178.50236511  194.86721802  146.08096313]

 ...

1990 Cost:  4.9197
Prediction:
 [ 148.15084839  186.88632202  179.6293335   195.81796265  144.46044922]
2000 Cost:  4.89449
Prediction:
 [ 148.15931702  186.8805542   179.63194275  195.81971741  144.45298767]
'''

0 Cost:  86542.5 
Prediction:
 [-110.57433319 -128.47401428 -128.95007324 -139.82521057  -97.31678009]
10 Cost:  1.42056 
Prediction:
 [ 149.66390991  184.30961609  179.24272156  195.7885437   141.25791931]
20 Cost:  0.627199 
Prediction:
 [ 150.45306396  185.25482178  180.17578125  196.8041687   141.97842407]
30 Cost:  0.626078 
Prediction:
 [ 150.45721436  185.25650024  180.17918396  196.80738831  141.97929382]
40 Cost:  0.624975 
Prediction:
 [ 150.45896912  185.25531006  180.17974854  196.80754089  141.97795105]
50 Cost:  0.623889 
Prediction:
 [ 150.46070862  185.25415039  180.18032837  196.80769348  141.97663879]
60 Cost:  0.622797 
Prediction:
 [ 150.46246338  185.25297546  180.18089294  196.80786133  141.97532654]
70 Cost:  0.621715 
Prediction:
 [ 150.46420288  185.2518158   180.18145752  196.80801392  141.97399902]
80 Cost:  0.620623 
Prediction:
 [ 150.46595764  185.25064087  180.18202209  196.8081665   141.97270203]
90 Cost:  0.619555 
Prediction:
 [ 150.46768188  185.24948

1040 Cost:  0.537333 
Prediction:
 [ 150.61387634  185.15171814  180.23048401  196.81886292  141.8634491 ]
1050 Cost:  0.536639 
Prediction:
 [ 150.61523438  185.15078735  180.23092651  196.81892395  141.86245728]
1060 Cost:  0.535947 
Prediction:
 [ 150.61659241  185.14988708  180.23136902  196.81898499  141.86149597]
1070 Cost:  0.535274 
Prediction:
 [ 150.61795044  185.14898682  180.23182678  196.8190918   141.86051941]
1080 Cost:  0.53458 
Prediction:
 [ 150.61930847  185.14808655  180.23226929  196.81913757  141.85954285]
1090 Cost:  0.533904 
Prediction:
 [ 150.6206665   185.14720154  180.23272705  196.81922913  141.8585968 ]
1100 Cost:  0.533238 
Prediction:
 [ 150.62197876  185.14628601  180.2331543   196.8192749   141.85760498]
1110 Cost:  0.532559 
Prediction:
 [ 150.62333679  185.145401    180.2335968   196.8193512   141.85665894]
1120 Cost:  0.531898 
Prediction:
 [ 150.62466431  185.14450073  180.23403931  196.81942749  141.85569763]
1130 Cost:  0.531234 
Prediction:
 [ 1

1850 Cost:  0.49014 
Prediction:
 [ 150.71382141  185.08522034  180.26367188  196.82273865  141.79321289]
1860 Cost:  0.489649 
Prediction:
 [ 150.7149353   185.08447266  180.26403809  196.82275391  141.79244995]
1870 Cost:  0.489168 
Prediction:
 [ 150.71603394  185.08375549  180.26441956  196.82276917  141.79170227]
1880 Cost:  0.48869 
Prediction:
 [ 150.71714783  185.08300781  180.26480103  196.82281494  141.79093933]
1890 Cost:  0.488208 
Prediction:
 [ 150.71824646  185.08229065  180.26516724  196.8228302   141.79020691]
1900 Cost:  0.487731 
Prediction:
 [ 150.71936035  185.08157349  180.26553345  196.82287598  141.78945923]
1910 Cost:  0.487247 
Prediction:
 [ 150.72045898  185.08082581  180.26589966  196.82287598  141.78869629]
1920 Cost:  0.486776 
Prediction:
 [ 150.72154236  185.08009338  180.26626587  196.82289124  141.78794861]
1930 Cost:  0.48629 
Prediction:
 [ 150.72265625  185.07937622  180.26663208  196.82290649  141.78721619]
1940 Cost:  0.485822 
Prediction:
 [ 150

'\n0 Cost:  19614.8\nPrediction:\n [ 21.69748688  39.10213089  31.82624626  35.14236832  32.55316544]\n10 Cost:  14.0682\nPrediction:\n [ 145.56100464  187.94958496  178.50236511  194.86721802  146.08096313]\n\n ...\n\n1990 Cost:  4.9197\nPrediction:\n [ 148.15084839  186.88632202  179.6293335   195.81796265  144.46044922]\n2000 Cost:  4.89449\nPrediction:\n [ 148.15931702  186.8805542   179.63194275  195.81971741  144.45298767]\n'